### ISSUE TITLE
Petit bug

### ISSUE THREAD

**Issue by tristanbouchard** [Jouca/Tetris#3]
Bonjour,

En voulant tester le jeu, je n'ai pas pu aller jusqu'à mon niveau max, j'ai eu un petit bug : les pièces s'affichent tout en haut sans descendre et passent à la suivante.
Je pouvais en garder une en réserve mais aucun changement au score, en ligne... J'aurais pu ne jamais perde \o/

Voir les captures d'écran.

PS c'est un petit score, je dois pouvoir faire mieux car la vitesse me semble moins rapide que sur Game Boy sans compter la pièce de réserve (pas présent) et la vue des prochaines pièces (seulement 1)!

![Capture d’écran de 2022-02-21 14-44-06](https://user-images.githubusercontent.com/98639468/154967213-84789ef3-c7aa-454c-ae48-5b0812a320f4.png)
![Capture d’écran de 2022-02-21 14-43-37](https://user-images.githubusercontent.com/98639468/154967221-ebe4a26e-faaf-4c1c-bd44-7cee10b6dd70.png)
![Capture d’écran de 2022-02-21 14-43-36](https://user-images.githubusercontent.com/98639468/154967223-9f664183-0786-4911-a981-586b17056cdd.png)

![Capture d’écran de 2022-02-21 14-43-59](https://user-images.githubusercontent.com/98639468/154967219-0fe4ed16-76df-428e-9473-7c412c8e7f7f.png)
/

**Comment by Jouca** [comment]
Bonjour @tristanbouchard,

Merci pour votre rapport, nous sommes désolé que ce problème ait pu engendrer une défaillance lors de votre partie TwT

Il est probable que le problème ait déjà été réglé selon @periergeia et le commit devrait arriver d'ici peu !

Diego
